[tg_bot]
token = ""
admin_ids = []
developer_id = 123
admin_channel_id = -123
channel_for_doc_drawing_orders = -123
use_redis = true

[db]
host = "localhost"
port = 5432
password = "user"
user = "user"
name = "template_shop"
echo = true

[redis]
host = "localhost"
port = 6379
database = 5

[payment]
crypto_token = "123"
