"""Removed link_password column

Revision ID: fe2674e0c29c
Revises: 4eb09b0e943e
Create Date: 2024-09-03 15:08:15.039359

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fe2674e0c29c"
down_revision = "4eb09b0e943e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "link_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("link_password", sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
