"""Made english default for new users

Revision ID: 49d2eba96f66
Revises: fe2674e0c29c
Create Date: 2025-04-19 11:17:27.259313

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49d2eba96f66"
down_revision = "fe2674e0c29c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE IF EXISTS public."user" ALTER COLUMN lang_code SET DEFAULT \'en\'::langcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE IF EXISTS public."user" ALTER COLUMN lang_code SET DEFAULT \'ru\'::langcode')
    # ### end Alembic commands ###
